leftnav:
- identifier: 1e1b3ae9-8ab5-c0ef-5bb6-29a9b821d183
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: aecfd950-499e-3466-83cf-602c07fc2f45
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 8c5688d6-eb11-ac8f-e419-235dcb4a98f3
  name: Assignments
  url: /pages/assignments
  weight: 30
- identifier: 9f0a8a9e-1327-8983-9f90-71c8b348b9a8
  name: Projects
  url: /pages/projects
  weight: 40
- identifier: 60acbfcf-f087-efb6-9b36-5acdb9a80fda
  name: Study Materials
  url: /pages/study-materials
  weight: 50
